using DanmakuBaseExpansion.Cards.MainDeck;
using DanmakuCardGameEngine.Enums;
using DanmakuCardGameEngine.Models.Deck;

namespace DanmakuBaseExpansion.Decks {
    internal static class BaseMainDeck {
        public static IMainDeck Get() => new MainDeck() {
            // new OneUp(1, Seasons.Winter),
            // new OneUp(2, Seasons.Autumn),
            // new Bomb(3, Seasons.Summer),
            // new Bomb(4, Seasons.Autumn),
            // new Bomb(5, Seasons.Winter),
            // new Bomb(6, Seasons.Spring),
            // new Borrow(7, Seasons.Spring),
            // new Borrow(8, Seasons.Summer),
            // new CaptureSpellCard(9, Seasons.Winter),
            new Focus(10, Seasons.Autumn),
            new Focus(11, Seasons.Summer),
            new Graze(12, Seasons.Spring),
            new Graze(13, Seasons.Spring),
            new Graze(14, Seasons.Spring),
            new Graze(15, Seasons.Spring),
            new Graze(16, Seasons.Summer),
            new Graze(17, Seasons.Summer),
            new Graze(18, Seasons.Summer),
            new Graze(19, Seasons.Autumn),
            new Graze(20, Seasons.Autumn),
            new Graze(21, Seasons.Autumn),
            new Graze(22, Seasons.Winter),
            new Graze(23, Seasons.Winter),
            new Graze(24, Seasons.Winter),
            new Graze(25, Seasons.Winter),
            // new Grimoire(26, Seasons.Autumn),
            // new Grimoire(27, Seasons.Summer),
            // new Kourindou(28, Seasons.Winter),
            // new LaserShot(29, Seasons.Summer),
            // new LastWord(30, Seasons.Summer),
            // new MasterPlan(31, Seasons.Autumn),
            // new Melee(32, Seasons.Winter),
            // new MiniHakkero(33, Seasons.Summer),
            // new Party(34, Seasons.Spring),
            new Power(35, Seasons.Winter),
            new Power(36, Seasons.Winter),
            new Power(37, Seasons.Spring),
            new Power(38, Seasons.Spring),
            new Power(39, Seasons.Summer),
            new Power(40, Seasons.Autumn), 
            // new SealAway(41, Seasons.Summer),
            // new SealAway(42, Seasons.Autumn),
            // new SealAway(43, Seasons.Winter),
            // new SealAway(44, Seasons.Spring),
            new Shoot(45, Seasons.Spring),
            new Shoot(46, Seasons.Spring),
            new Shoot(47, Seasons.Spring),
            new Shoot(48, Seasons.Spring),
            new Shoot(49, Seasons.Spring),
            new Shoot(50, Seasons.Spring),
            new Shoot(51, Seasons.Summer),
            new Shoot(52, Seasons.Summer),
            new Shoot(53, Seasons.Summer),
            new Shoot(54, Seasons.Summer),
            new Shoot(55, Seasons.Summer),
            new Shoot(56, Seasons.Summer),
            new Shoot(57, Seasons.Autumn),
            new Shoot(58, Seasons.Autumn),
            new Shoot(59, Seasons.Autumn),
            new Shoot(60, Seasons.Autumn),
            new Shoot(61, Seasons.Autumn),
            new Shoot(62, Seasons.Autumn),
            new Shoot(63, Seasons.Winter),
            new Shoot(64, Seasons.Winter),
            new Shoot(65, Seasons.Winter),
            new Shoot(66, Seasons.Winter),
            new Shoot(67, Seasons.Winter),
            new Shoot(68, Seasons.Winter),
            // new SorcerersSutraScroll(69, Seasons.Autumn),
            // new SpiritualAttack(70, Seasons.Spring),
            // new SpiritualAttack(71, Seasons.Spring),
            // new SpiritualAttack(72, Seasons.Summer),
            // new SpiritualAttack(73, Seasons.Summer),
            // new SpiritualAttack(74, Seasons.Autumn),
            // new SpiritualAttack(75, Seasons.Winter),
            // new Stopwatch(76, Seasons.Winter),
            // new SupernaturalBorder(77, Seasons.Spring),
            // new SupernaturalBorder(78, Seasons.Spring),
            // new Tempest(79, Seasons.Autumn),
            // new Voile(80, Seasons.Autumn)
        };
    }
}